version: '3.8'

services:
  centour_db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=centour_user
      - POSTGRES_PASSWORD=centour_password
      - POSTGRES_DB=centour_db
  centour:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://centour_user:centour_password@centour_db:5432/centour_db
    depends_on:
      - centour_db

volumes:
  postgres_data: